version: '3'  # version of compose format

services:
  web:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/todo
    links:
      - db
  db:
    image: mongo:3.0.2
  consumer:
    image: php:apache
    volumes:
      - ./consumer:/var/www/html
    ports:
      - "5001:80"  # host:container
    depends_on:
      - web  # website is not going to work unless laptop-service is running
